apiVersion: v1
kind: Pod
metadata:
  name: shinyproxy
  labels:
    ci: shinyproxy-build
spec:
  containers:
    - name: containerproxy-build
      image: public.ecr.aws/docker/library/maven:3-eclipse-temurin-17-focal
      command:
        - cat
      tty: true
      resources:
        requests:
          ephemeral-storage: "20Gi"
          memory: "2Gi"
          cpu: "1.0"
        limits:
          memory: "4Gi"
          cpu: "1.5"
          ephemeral-storage: "20Gi"
