name: Tests

on:
  push:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java:
          - 17

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Setup Docker
        run: sudo apt-get -qq -y install conntrack socat ; nohup socat TCP-LISTEN:2375,reuseaddr,fork UNIX-CONNECT:/var/run/docker.sock &
      - name: Pull Image
        run: docker pull openanalytics/shinyproxy-integration-test-app
      - name: Build with Maven
        run: mvn -U clean install -DskipTests
      - name: Run Tests
        run: mvn test

  dependency:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Run Dependency Check
        run: mvn -Powasp-dependency-check verify -DskipTests
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: dependency-check-report
          path: target/dependency-check-report.html
